environments:
  - name: dev
    configs:
      endpoints:
          production:
              url: 'https://pickme.swagger.io/v2/chandimacba'
      deploymentEnvironments:
          - displayOnDevportal: true
            deploymentEnvironment: Default
            deploymentVhost : localhost